### PR TITLE
Id equal to model name when root is used in Entity

### PR DESCRIPTION
**Pull request by aitortomas**
See issue #250

### CODE REVIEW

**Comment by aitortomas** [comment]
With my fix, the schema in Swagger-UI would show with the class name from the entity.
Should it show the defined "root" if existing?
I am open to discussion.

**Comment by dblock** [comment]
So this was a misunderstanding of the spec?

Fix the build please (rubocop), update changelog.

**Comment by aitortomas** [comment]
Yes, it looks like a misunderstanding of the specs, at least for the case in which root is defined in the entities.

**Comment by dblock** [comment]
Merged via https://github.com/tim-vandecasteele/grape-swagger/commit/834ee0111e2631e8359f429c9184207579aa940c.

**Comment by iangreenleaf** [comment]
This now breaks my entity references because `root` gets used in the `models` object but not in `apis[].operations[].type`.

Should `@root` be used at all by default? Seems like it's internal data and meant for defining the formatting, not for defining the model ID.

**Comment by aitortomas** [comment]
I see what you mean, I can put the root logic inside the `parse_entity_name` method and it will work.
Despite that, I am open to discussion regarding if root should actually be used or not.

**Comment by dblock** [comment]
@iangreenleaf and @aitortomas Can you please help resolve this? Lets make sure we don't break backward compatibility or have a way out documented in UPGRADING?

**Comment by aitortomas** [comment]
I can add the root logic to the `parse_entity_name` method but then Rubocop complains:
lib/grape-swagger.rb:9:3: C: Class definition is too long. [511/509]
  class API
  ^^^^^
lib/grape-swagger.rb:173:7: C: Assignment Branch Condition size for create_documentation_class is too high. [360.7/360]
      def create_documentation_class
      ^^^
lib/grape-swagger.rb:173:7: C: Method has too many lines. [383/381]
      def create_documentation_class
      ^^^

**Comment by aitortomas** [comment]
Check https://github.com/tim-vandecasteele/grape-swagger/pull/254

**Comment by iangreenleaf** [comment]
Looks like #254 is a good fix if we're keeping the root logic. I'm still on the side of removing it, though. @dblock @aitortomas do either of you know why it was added in the first place? I found the commit that introduced it (2747bb2c) but I don't know if there's an associated issue and discussion.

It seems like the kind of behavior that might be convenient for some apps, but not everyone in general. The fact that I want my output wrapped as `{xyz: {…}}` doesn't necessarily mean I want `xyz` to be my canonical model name.

Removing this *would* break backwards compatibility with anyone depending on it, but I think we could work out a simple upgrade path. For example, people who wanted this behavior could redefine `entity_name` to something like this:

```ruby
def entity_name
  super || @root
end
```

**Comment by dblock** [comment]
To answer your question, honestly I don't know the background for this.

**Pull request closed without merging**
