### PR TITLE
Treat Symbol as string in params parsing

### PR DESCRIPTION
**Pull request by ypresto**
`type: Symbol` is sometimes useful when accepting enum params.

Currently this library treats it as custom data type sent as body, but it must be same as string in layer of http.

This PR make Symbol treated as string in swagger doc (with only 2 lines!).

Thanks for great product :)

### CODE REVIEW

**Comment by ypresto** [comment]
```
Class definition is too long. [399/397]
```

Oh, no... How do I fix it?

**Comment by dblock** [comment]
For Rubocop, just run `rubocop --auto-gen-config`.

**Comment by dblock** [comment]
This also needs a CHANGELOG entry please. 

You should write a higher level integration test, too (something about the API and the generated swagger doc).

**Comment by ypresto** [comment]
Added test for generated doc, and CHANGELOG :)

**Comment by dblock** [comment]
Looks great!

**Pull request merged**
