### PR TITLE
Range values

### PR DESCRIPTION
**Pull request by u2**
Supplying a range to the :values option in grape v0.10.1, so maybe need to update grape version to v0.10.1 .

### CODE REVIEW

**Comment by dblock** [comment]
This needs tests and a CHANGELOG entry please.

**Comment by dblock** [comment]
Could you please fix CI (Rubocop) and rebase? Thx.

**Comment by u2** [comment]
#210 
Pls closed this merge.I open another one.Thx.

**Comment by dblock** [comment]
Closed via https://github.com/tim-vandecasteele/grape-swagger/pull/210.

**Pull request closed without merging**
