### PR TITLE
Allow callables for hidden setting

### PR DESCRIPTION
**Pull request by zbelzer**
I would like to expose a different set of API features per client, so having the documentation conditionally hidden is very useful to me.

Not sure if there's a more compact way to say the same thing.

Also, RubyCop is complaining because I added three lines. Is this configured limitation or am I just so lucky that we were at the exact boundary before?

### CODE REVIEW

**Comment by dblock** [comment]
For rubocop run `rubocop --auto-gen-config`.

**Comment by dblock** [comment]
Squash your commits please?

**Comment by zbelzer** [comment]
Squashed. Rubocop updated and it looks like travis is happy.

**Comment by dblock** [comment]
We should probably also document this in README, what do you think?

**Comment by zbelzer** [comment]
Docs added.

**Comment by dblock** [comment]
Merged, thank you.

**Comment by swistaczek** [comment]
:+1:

**Comment by synth** [comment]
This does not seem to allow conditional based on request headers or parameters, right? Seems like it would be a simple fix to pass them along. Essentially, I have endpoints that use a custom Oauth "trusted" scope and I only want to show endpoints when a token is used that has that scope. Or perhaps is there another way to show/hide endpoints based on matching oauth scope?

**Comment by zbelzer** [comment]
I would imagine you just need to pass contextual information to `call` in each location. Not sure where whatever information you are using is kept, but you can figure out if it's available by putting in a breakpoint before `route.route_hidden.respond_to?(:call) ? route.route_hidden.call : route.route_hidden`

**Pull request merged**
