### PR TITLE
Fix for Grape 0.12.0 with :hide_format

### LINKED ISSUE #262: hide_format not working with grape 0.12.0
```
gem 'grape', '0.12.0'
gem 'grape-swagger', '0.10.1'
gem 'grape-swagger-rails', :git => 'git://github.com/BrandyMint/grape-swagger-rails.git'
```

`.(format)`is added to the url even if `hide_format` is set to `true`.

### PR DESCRIPTION
**Pull request by mattolson**
* Grape 0.12.0 changed the paths for api endpoints that have a single
  format. See https://github.com/intridea/grape/pull/1001/files
* This change updates the way we reformat the paths for Swagger to
  account for this.
* Fixes #262

### CODE REVIEW

**Comment by mattolson** [comment]
Note that you should merge #272 first to get the tests to run with Grape 0.12.0 on Travis.

**Comment by dblock** [comment]
Thanks, merging.

**Comment by huanzhang** [comment]
Has this commit upload to rubygems.org?

**Comment by dblock** [comment]
No @huanzhang I will make a release soon.

**Pull request merged**
