### PR TITLE
Update to Ruby 2.2.2

### PR DESCRIPTION
**Pull request by tmilewski**

### CODE REVIEW

**Comment by dblock** [comment]
Why do we even need this file? I think it should be removed and 2.2.2 added to https://github.com/tim-vandecasteele/grape-swagger/blob/master/.travis.yml, no?

**Comment by mattolson** [comment]
Agreed, use of `.ruby-version` is really a local concern. Rather than changing it, It should be added to `.gitignore`.

**Comment by dblock** [comment]
I would take a PR, please.

**Comment by dblock** [comment]
Closing in favor of https://github.com/tim-vandecasteele/grape-swagger/pull/288.

**Pull request closed without merging**
