### PR TITLE
Changelog and rspec for: Fixed the bug where 'is_array' in the return entity is ignored

### PR DESCRIPTION
**Pull request by frodrigo**
Changelog and rspec for: Fixed the bug where 'is_array' in the return entity is ignored

### CODE REVIEW

**Comment by dblock** [comment]
Build needs to be fixed and commits squashed, thanks.

**Comment by frodrigo** [comment]
I stashed fix for my changes, but there is issues with the main code

**Comment by dblock** [comment]
The rubocop problem is easy, just run `rubocop --auto-gen-config`.

**Comment by dblock** [comment]
Merged via https://github.com/tim-vandecasteele/grape-swagger/commit/768454bac676417ad1fce0d1da2bf82835fbc6c6.

**Pull request closed without merging**
