### PR TITLE
Allow for entity documentation to support an array of entities

### PR DESCRIPTION
**Pull request by matt61**
This allows for using the $ref element in the swagger spec to display nested relationships.

### CODE REVIEW

**Comment by onemanstartup** [comment]
What about this pull request?

**Comment by dblock** [comment]
Look to ^^^ from @matt61 (or anyone else who wants to finish this).

**Comment by swistaczek** [comment]
@matt61 +1

**Comment by dblock** [comment]
I think https://github.com/tim-vandecasteele/grape-swagger/pull/217 closes this, but there's a lot more code here doing all kinds of things. Please reopen/comment if I am missing something.

**Pull request closed without merging**
